### ISSUE TITLE
Error: ENOENT: no such file or directory (ember-cli 2.7+)

### ISSUE THREAD

**Issue by oniofchaos** [kiwiupover/ember-cli-spinjs#58]
When upgrading from ember-cli 2.6 to ember-cli 2.7, I get the following error when running my app

`Error: ENOENT: no such file or directory, stat 'path/to/my/project/tmp/source_map_concat-input_base_path-0XpSiVgM.tmp/0/undefined/spin.js/spin.js'`

When I remove `ember-cli-spinjs` from `package.json`, the issue goes away.

Any idea what could be going on? Any advice is appreciated.

**Comment by kiwiupover** [comment]
My first thought is that you don't have the bower package installed for spin.js

https://github.com/kiwiupover/ember-cli-spinjs/blob/master/index.js#L14

`bower install spin.js` should fix your issue.

**Comment by oniofchaos** [comment]
I thought that as well, but neither command fixes the issue.

**Comment by kiwiupover** [comment]
@oniofchaos I hope v1.1.0  will fix your issue. 

I have updated `ember-cli-spinjs` to use npm instead of bower. 

So you will need to delete `spin.js` from your `bower.json` file and run `npm i` 

Let me know you get on. 

Cheers
Dave

**Comment by oniofchaos** [comment]
Looks like that solved it, thanks!

**Comment by kiwiupover** [comment]
Perfect!


On October 31, 2016 at 4:40:39 PM, Dillon Welch (notifications@github.com)
wrote:

Looks like that solved it, thanks!

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/kiwiupover/ember-cli-spinjs/issues/58#issuecomment-257451699>,
or mute the thread
